<font size=10>**GENERAL DATA PREPROCESSING**</font> <a class="anchor" id='title'></a> 


*«notebook description»*

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a> 
- [1. Imports](#P1)
- [2. Data](#P2)
- [3. General Text Preprocessing](#P3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="P1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [2]:
import sys
import os
import pandas as pd

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from general_preprocessing import *

# <font color='#BFD72F' size=6>**2. Data**</font> <a class="anchor" id="P2"></a>
  
[Back to TOC](#toc)

In [3]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [4]:
dataset_original

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...
...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...

In [5]:
dataset_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

| 🏷️ **Column Name** | 📝 **Description** |
|:-------------------|:-------------------|
|**title** | Name of the restaurant |
|**categoryName** | Labels that describe the restaurant's cuisine type |
|**website** | URL of the restaurant's webpage |
|**url** | URL of the restaurant's Google Maps page |
|**reviewsCount** | Total number of reviews for the restaurant at the time of scraping |
|**stars** | Customer rating (1 to 5) |
|**text** | Text of the review |

In [6]:
dataset = dataset_original.copy()

# <font color='#BFD72F' size=6>**3. General Text Preprocessing**</font> <a class="anchor" id="P3"></a>
  
[Back to TOC](#toc)

In [7]:
# TODO: test the preprocessing pipeline
dataset['cleaned_review_body'] = dataset['text'].apply(
    lambda x: main_pipeline(
        raw_text=x,
        no_stopwords=True,
        stopwords_tokeep = ['again'],
        extra_stopwords=[],
        convert_diacritics=True,
        lowercase=True,
        lemmatized=True,
        list_pos=['n', 'v', 'a', 'r', 's'],
        stemmed=False,
        pos_tags_list='no_pos',
        tokenized_output=False,
        no_emojis=True,
        no_hashtags=True,
        hashtag_retain_words=True,
        no_newlines=True,
        no_urls=True,
        no_punctuation=True,
        normalized_repeated_chars=True
    )
)

In [8]:
# example output
dataset[['text', 'cleaned_review_body']].iloc[53].values

array(['Excellent food and vibe - our server seemed to be in a rush though. The oysters and the branzino were excellent!',
       'excellent food vibe server seem rush though oyster branzino excellent'],
      dtype=object)

In [11]:
dataset['tokenized_review_body'] = dataset['cleaned_review_body'].apply(
    lambda x: main_pipeline(
        raw_text=x,
        no_stopwords=False,
        stopwords_tokeep = [],
        extra_stopwords=[],
        convert_diacritics=False,
        lowercase=False,
        lemmatized=False,
        list_pos=['n', 'v', 'a', 'r', 's'],
        stemmed=False,
        pos_tags_list='no_pos',
        tokenized_output=True,
        no_emojis=False,
        no_hashtags=False,
        hashtag_retain_words=False,
        no_newlines=False,
        no_urls=False,
        no_punctuation=False,
        normalized_repeated_chars=False
    )
)

In [12]:
dataset[['text', 'cleaned_review_body', 'tokenized_review_body']].iloc[53].values

array(['Excellent food and vibe - our server seemed to be in a rush though. The oysters and the branzino were excellent!',
       'excellent food vibe server seem rush though oyster branzino excellent',
       list(['excellent', 'food', 'vibe', 'server', 'seem', 'rush', 'though', 'oyster', 'branzino', 'excellent'])],
      dtype=object)

In [13]:
cooc_matrix = cooccurrence_matrix_sentence_generator(dataset['tokenized_review_body'], sentence_cooc=False, window_size=1)

Computing co-occurrences: 100%|██████████| 53566/53566 [00:01<00:00, 42914.35it/s]

In [14]:
display(cooc_matrix)

,food,good,great,service,order,place,go,get,time,come,...,nailed,bonzinho,delicious~~,yummo,captd,arby,smdack,ballin,geary,foosball
food,148,4345,5144,2350,443,378,234,632,294,451,...,0,0,0,0,0,0,0,0,0,0
good,4345,244,203,1903,116,479,110,268,204,72,...,0,0,0,0,0,0,0,0,0,0
great,5144,203,98,3454,61,1069,71,96,288,45,...,0,0,0,0,0,0,0,0,0,0
service,2350,1903,3454,38,61,85,133,95,101,54,...,0,0,0,0,0,0,0,0,0,0
order,443,116,61,61,148,405,331,477,253,138,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
arby,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
smdack,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ballin,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
geary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
foosball,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
vocabulary = dataset['tokenized_review_body'].explode().unique()
vocabulary

array(['one', 'word', 'amaze', ..., 'tartufo', 'ryleigh', 'francaise'],
      dtype=object)

In [23]:
len(vocabulary)

25391