# **GENERAL DATA PREP**

*One-time text cleaning applied to the entire dataset (e.g., lowercasing, removing noise/HTML tags, universal stop word removal, basic tokenization). Finalizing the train/test/validation split.*

In [ ]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

## Libraries

In [ ]:
import sys
import os
import pandas as pd

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from utils import *
from general_preprocessing import *

## Data

In [ ]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [ ]:
dataset_original

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...
...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...

In [ ]:
dataset_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

| 🏷️ **Column Name** | 📝 **Description** |
|:-------------------|:-------------------|
|**title** | Name of the restaurant |
|**categoryName** | Labels that describe the restaurant's cuisine type |
|**website** | URL of the restaurant's webpage |
|**url** | URL of the restaurant's Google Maps page |
|**reviewsCount** | Total number of reviews for the restaurant at the time of scraping |
|**stars** | Customer rating (1 to 5) |
|**text** | Text of the review |

In [ ]:
dataset = dataset_original.copy()

In [ ]:
dataset[dataset['title'] == 'Johnny Rockets']['reviewsCount'].unique()

array([   5, 1126])

In [ ]:
# TODO: Preprocess reviewsCount inconsistencies, keep always the higher value in case the same restaurant has different values

dataset = dataset_original.copy()

# Replace each restaurant's reviewsCount with the max reviewsCount for that restaurant
dataset['reviewsCount'] = dataset.groupby('title')['reviewsCount'].transform('max')

In [ ]:
dataset[dataset['title'] == 'Johnny Rockets']['reviewsCount'].unique()

array([1126])

## 2. Preprocessing

In [ ]:
dataset['cleaned_review_body'] = dataset['text'].apply(
    lambda x: main_pipeline(
        raw_text=x,
        no_stopwords=True,
        custom_stopwords=['example1', 'example2'],
        convert_diacritics=True,
        lowercase=True,
        lemmatized=True,
        list_pos=['n', 'v', 'a', 'r', 's'],
        stemmed=False,
        pos_tags_list='no_pos',
        tokenized_output=False,
        no_emojis=True,
        no_hashtags=True,
        hashtag_retain_words=True,
        no_newlines=True,
        no_urls=True,
        no_punctuation=True
    )
)

In [ ]:
dataset[['text', 'cleaned_review_body']].iloc[53].values

array(['Excellent food and vibe - our server seemed to be in a rush though. The oysters and the branzino were excellent!',
       'excellent food vibe - server seem rush though oyster branzino excellent'],
      dtype=object)

In [ ]:
preproc_sentences = [nltk.word_tokenize(text) for text in dataset['cleaned_review_body']]

In [ ]:
preproc_sentences

[['one',
  'word',
  'amaze',
  'red',
  'fish',
  'halibut',
  'fry',
  'rice',
  'broccolini',
  'dish',
  'die',
  'chef',
  'brandon',
  'fantastic',
  'definitely',
  'visit',
  'again'],
 ['first', 'time', 'food', 'great', 'waiter', 'excellent'],
 ['recently',
  'pleasure',
  'din',
  'optimist',
  'atlanta',
  'ga',
  'let',
  'tell',
  'absolute',
  'treat',
  'moment',
  'walk',
  'know',
  'fantastic',
  'din',
  'experience',
  'first',
  'restaurant',
  'offer',
  'indoor',
  'outdoor',
  'seat',
  'option',
  'make',
  'versatile',
  'choice',
  'occasion',
  'whether',
  'prefer',
  'cozy',
  'ambiance',
  'indoor',
  'din',
  'area',
  'refresh',
  'outdoor',
  'patio',
  'optimist',
  'get',
  'cover',
  'kick',
  'even',
  'order',
  'signature',
  'margarita',
  'disappoint',
  'cocktail',
  'expertly',
  'craft',
  'perfectly',
  'balance',
  'incredibly',
  'tasty',
  'set',
  'tone',
  'delightful',
  'meal',
  'ahead',
  'one',
  'thing',
  'stand',
  'right',
  'start',
  'warm',
  'freshly',
  'bake',
  'bread',
  'serve',
  'appetizer',
  'tempt',
  'couldnt',
  'resist',
  'indulge',
  'bread',
  'soft',
  'warm',
  'delightful',
  'crust',
  '-',
  'excellent',
  'teaser',
  'culinary',
  'delight',
  'await',
  'u',
  'main',
  'course',
  'decide',
  'share',
  'lobster',
  'shrimp',
  'dish',
  'decision',
  'regret',
  'seafood',
  'impeccably',
  'prepare',
  'succulent',
  'burst',
  'flavor',
  'dish',
  'perfect',
  'balance',
  'season',
  'portion',
  'size',
  'right',
  'leave',
  'u',
  'crave',
  'throughout',
  'meal',
  'waiter',
  'provide',
  'exceptional',
  'service',
  'attentive',
  'friendly',
  'knowledgeable',
  'menu',
  'make',
  'excellent',
  'recommendation',
  'professionalism',
  'add',
  'overall',
  'enjoyment',
  'din',
  'experience',
  'end',
  'even',
  'already',
  'plan',
  'next',
  'visit',
  'optimist',
  'safe',
  'say',
  'restaurant',
  'catapult',
  'top',
  'three',
  'favorite',
  'din',
  'spot',
  'atlanta',
  'combination',
  'delectable',
  'food',
  'outstanding',
  'service',
  'welcome',
  'atmosphere',
  'truly',
  'hard',
  'beat',
  'optimist',
  'undoubtedly',
  'place',
  'go',
  'youre',
  'look',
  'place',
  'enjoy',
  'incredible',
  'meal',
  'fantastic',
  'drink',
  'memorable',
  'din',
  'experience',
  'atlanta',
  'cant',
  'recommend',
  'enough',
  'cant',
  'wait',
  'return',
  'another',
  'delicious',
  'meal'],
 ['beautiful',
  'atmosphere',
  'delicious',
  'food',
  'food',
  'wasnt',
  'flavorful',
  'overall',
  'food',
  'great',
  'oyster',
  'best',
  'ive',
  'mussel',
  'sauce',
  'subtle',
  'kick',
  'flavorful',
  'thing',
  'disappoint',
  'side',
  'fresh',
  'little',
  'bland',
  'get',
  'hush',
  'puppy',
  'afterwards',
  'good',
  'taste',
  'sweet',
  'sweet',
  'light',
  'airy',
  'service',
  'also',
  'great',
  'begin',
  'end'],
 ['wonderful',
  'dinner',
  'optimist',
  'group',
  '9',
  'great',
  'meal',
  'oyster',
  'cocktail',
  'delicious'],
 ['atmosphere',
  'lovely',
  'service',
  'exceptional',
  'wasnt',
  'fond',
  'food',
  'nothing',
  'try',
  'stand',
  'least',
  'enough',
  'another',
  'visit',
  'everything',
  'else',
  'good'],
 ['best', 'oyster', 'ever'],
 ['always',
  'good',
  'time',
  'quality',
  'drink',
  'food',
  'optimist',
  'yet',
  'disappoint'],
 ['great',
  'food',
  'service',
  'greeterhost',
  'bartender',
  'waiter',
  'awesome',
  'experience'],
 ['4th',
  'time',
  'go',
  'lady',
  'attempt',
  'try',
  'almost',
  'everything',
  'menu',
  'date',
  'night',
  'top',
  'choice'],
 ['first',
  'time',
  'town',
  'guest',
  'atmosphere',
  'stun',
  'service',
  'impressive',
  'think',
  'food',
  'mediocre',
  'best',
  'incredibly',
  'overprice',
  'aware',
  'restaurant',
  'sit',
  'shadow',
  'new',
  'construction',
  'make',
  'appeal',
  'folk',
  'new',
  'neighborhood'],
 ['valet',
  'right',
  'next',
  'restaurant',
  'youre',
  'pull',
  'share',
  'park',
  'deck',
  'optimist',
  'superica',
  'west',
  'midtown',
  'howell',
  'mill',
  'road',
  'text',
  'valet',
  'car',
  'ready',
  'walk',
  'paying',
  'tip',
  'also',
  'do',
  'phone',
  'reservation',
  'friend',
  'birthday',
  'menu',
  'happy',
  'birthday',
  'stamp',
  'like',
  'lot',
  'food',
  'service',
  'good',
  'always',
  'start',
  'dinner',
  '7',
  'light',
  'restaurant',
  'still',
  'well',
  'light',
  'dim',
  'time',
  'go',
  'late',
  'night',
  'good',
  'light',
  'think',
  'cause',
  'visual',
  'issue',
  'people',
  'read',
  'menu',
  'ambience',
  'good',
  'bite',
  'loud',
  'since',
  'place',
  'pack',
  'friday',
  'night',
  'speak',
  'bite',
  'hear',
  'appetizer',
  '-',
  'roasted',
  'oyster',
  'really',
  'good',
  'menu',
  'always',
  'order',
  '-',
  'dozen',
  'raw',
  'oyster',
  'round',
  'island',
  'bay',
  'shores',
  '-',
  'blue',
  'crab',
  'claw',
  'theyre',
  'tiny',
  'tasty',
  '-',
  'pei',
  'mussel',
  '-',
  'whole',
  'shrimp',
  'la',
  'plancha',
  'big',
  'toast',
  '-',
  'spicy',
  'kale',
  'salad',
  'entree',
  '-',
  'roasted',
  'maine',
  'lobster',
  '-',
  'whole',
  'flounder',
  'dessert',
  'sorbet',
  'moment',
  'daiquiri',
  'portion',
  'bite',
  'small',
  'every',
  'dish',
  'lot',
  'appetizer',
  'leave',
  'full',
  'happy',
  'tummy',
  'youre',
  'seafood',
  'oyster',
  'place',
  'solid',
  'quality',
  'highly',
  'recommend'],
 ['restaurant',
  'deserve',
  '5',
  'star',
  'qualitytaste',
  'food',
  'service',
  'atmosphere',
  'however',
  'ive',
  'scallop',
  'many',
  'different',
  'restaurant',
  'price',
  'point',
  'admit',
  'small',
  'portion',
  'size',
  'purchase',
  'date',
  'doubt',
  'delicious',
  'could',
  'critique',
  'one',
  'thing',
  'portion',
  'size',
  'correlate',
  'price',
  'thats',
  'pay'],
 ['killer', 'atmosphere', 'food', 'amaze'],
 ['great', 'place'],
 ['go',
  'friend',
  'birthday',
  'party',
  'immediately',
  'love',
  'room',
  'food',
  'good',
  'interest',
  'wine',
  'list',
  'service',
  'although',
  'bite',
  'relax',
  'time',
  'efficient',
  'friendly',
  'nice',
  'even',
  'would',
  'go',
  'back'],
 ['oh',
  'word',
  'place',
  'amaze',
  'oyster',
  'variety',
  'delish',
  'service',
  'impeccable',
  'place',
  'inside',
  'super',
  'cute',
  'fish',
  'delicious',
  'drink',
  'perfect',
  'even',
  'park',
  'deck',
  'nearby',
  'highly',
  'recommend',
  'cant',
  'wait',
  'go',
  'back'],
 ['lobster', 'roll', 'rule'],
 ['park',
  'nightmare',
  'figure',
  'get',
  'inside',
  'food',
  'service',
  'delightful'],
 ['went',
  'birthday',
  'husband',
  'everyone',
  'nice',
  'give',
  'birthday',
  'dessert',
  'little',
  'cute',
  'bouquet',
  'really',
  'recommend',
  'shrimp',
  'la',
  'plancha',
  'amaze',
  'literally',
  'best',
  'shrimp',
  'dish'],
 ['reserve',
  'table',
  'advance',
  'day',
  'note',
  'cancelation',
  'within',
  '2',
  'day',
  'equal',
  '50',
  'charge',
  'per',
  'person',
  'finished',
  '1st',
  'appetizer',
  'drink',
  'arrive',
  'oysters',
  'spot',
  'order',
  '6',
  '4',
  '6',
  '9',
  'waitress',
  'friendly',
  'know',
  'quite',
  'bite',
  'menu',
  'preparation',
  'ordered',
  'bottle',
  'champagne',
  '88',
  'one',
  'glass',
  'ea',
  'pour',
  'tell',
  'rest',
  'would',
  'come',
  'ice',
  'u',
  'arrive',
  'finish',
  'entree',
  'cork',
  'bag',
  'go',
  'basmati',
  'fry',
  'rice',
  'side',
  'dish',
  'note',
  'egg',
  'however',
  'gairly',
  'large',
  'bowl',
  'rice',
  'come',
  'lump',
  'scramble',
  'egg',
  '3',
  'egg',
  'easy',
  'alot',
  'chunk',
  'fish',
  'dish',
  'enjoy',
  'egg',
  'duck',
  'fat',
  'poach',
  'swordfish',
  'serve',
  'pepperonata',
  'duck',
  'confit',
  'lady',
  'pea',
  'see',
  'image',
  'pepperonata',
  'bell',
  'pepper',
  'cook',
  'plenty',
  'voo',
  'generally',
  'red',
  'color',
  'sauce',
  'pea',
  'visible',
  'however',
  'abundant',
  'duck',
  'confit',
  'seem',
  'like',
  'duck',
  'stew',
  'try',
  'cut',
  'fish',
  'butter',
  'knife',
  '-',
  'zero',
  'evidence',
  'duck',
  'fat',
  'poach',
  'moisture',
  'within',
  'like',
  'eat',
  'porkloin',
  'well',
  'overcook',
  'extremely',
  'dry',
  'honestly',
  'uneatable',
  'hated',
  'return',
  'spouse',
  'note',
  'scallop',
  'perfectly',
  'cook',
  'cripsy',
  'potato',
  'saffron',
  'aioli',
  'taste',
  'like',
  'mustard',
  'rather',
  'saffron',
  'aioli',
  'make',
  'mayo',
  'atmosphere',
  'pleasant',
  '-',
  'note',
  'somewhat',
  'loud',
  'look',
  'romantic',
  'dinner',
  'truly',
  'hop',
  'would',
  'good',
  'review',
  'end',
  'tab',
  'switch',
  'neighbor',
  'table',
  'process',
  'like',
  'waited',
  'correct',
  'spent',
  '300',
  'tip'],
 ['great',
  'oyster',
  'easy',
  'valet',
  'wait',
  'staff',
  'time',
  'could',
  'button',
  'part',
  'great',
  'place'],
 ['valet',
  'parking',
  'great',
  'seafood',
  'drink',
  'def',
  'one',
  'favorite',
  'restaurant',
  'good',
  'oyster',
  'octopus',
  'fish'],
 ['excellent', 'food', 'service', 'atmosphere', 'good', 'little', 'loud'],
 ['gluten-free',
  'allergy',
  'aware',
  'great',
  'experience',
  'cant',
  'wait',
  'come',
  'back'],
 ['lobster',
  'roll',
  'great',
  'everything',
  'else',
  'unremarkably',
  'mediocre',
  'bookmark',
  'time',
  'finally',
  'get',
  'chance',
  'visit',
  'really',
  'hop',
  'would',
  'five',
  'star',
  'experience',
  'leave',
  'unimpressed',
  'still',
  'hungry',
  'fry',
  'oyster',
  'didnt',
  'taste',
  'right',
  'hush',
  'puppy',
  'flavor',
  'whatsoever'],
 ['favorite',
  'seafood',
  'restaurant',
  'atlanta',
  'enjoy',
  'oyster',
  'happy',
  'hour',
  'first',
  'time',
  'recently',
  'fun',
  'get',
  'several',
  'different',
  'type',
  'compare',
  'description',
  'taste',
  'experience'],
 ['unfortunately',
  'experience',
  'restaurant',
  'disappoint',
  'go',
  'celebrate',
  'birthday',
  'really',
  'excite',
  'try',
  'restaurant',
  'hear',
  'many',
  'nice',
  'thing',
  'experience',
  'alignment',
  'review',
  'hear',
  'first',
  'make',
  'reservation',
  'wait',
  'little',
  'bite',
  'seat',
  'seat',
  'cramp',
  'area',
  'scoot',
  'table',
  'another',
  'sit',
  'ask',
  'host',
  'another',
  'table',
  'say',
  'would',
  'check',
  'never',
  'come',
  'back',
  'ro',
  'offer',
  'update',
  'stay',
  'seat',
  'original',
  'table',
  'shortly',
  'realize',
  'table',
  'wobbly',
  'husband',
  'keep',
  'foot',
  'bottom',
  'keep',
  'drink',
  'still',
  'food',
  'take',
  'severely',
  'long',
  'time',
  'come',
  'hear',
  'waiter',
  'offer',
  'free',
  'appetizer',
  'table',
  'next',
  'u',
  'inconvenience',
  'offer',
  'anything',
  'u',
  'finally',
  'food',
  'come',
  'cold',
  'send',
  'back',
  'beautiful',
  'atmosphere',
  'great',
  'menu',
  'option',
  'bad',
  'experience',
  'celebrate',
  'birthday',
  'again'],
 ['one', 'best', 'restaurant', 'atlanta'],
 ['friend',
  'come',
  'celebrate',
  'partner',
  'birthday',
  'friday',
  'night',
  'service',
  'outstanding',
  'thank',
  'justin',
  'make',
  'night',
  'special',
  'go',
  'extra',
  'mile',
  'u',
  'reflection',
  'service',
  'ever',
  'strictly',
  'quality',
  'control',
  'kitchen',
  'responsibility',
  'everyone',
  'party',
  'sick',
  'food',
  'poison',
  'day',
  'since',
  'meal',
  'ive',
  'ill',
  'ive',
  'call',
  'work',
  'day',
  'cant',
  'keep',
  'food',
  'spend',
  'pretty',
  'penny',
  'expect',
  'high',
  'quality',
  'food',
  'im',
  'disappoint',
  'suffer',
  'poison',
  'suppose',
  'fun',
  'birthday',
  'weekend',
  'consume',
  'illness',
  'whoever',
  'responsible',
  'quality',
  'control',
  'behind',
  'kitchen',
  'need',
  'hold',
  'accountable'],
 ['really',
  'great',
  'seafood',
  'cheap',
  'fair',
  'price',
  'quality',
  'wife',
  'enjoy',
  'oyster',
  'artic',
  'char',
  'scallop',
  'great',
  'side',
  'dish',
  'things',
  'improve',
  'restaurant',
  'get',
  'quite',
  'loud',
  'dessert',
  'soo',
  'great'],
 ['neighbor',
  'go',
  'optimist',
  'sunday',
  'even',
  'celebrate',
  'new',
  'job',
  'waitress',
  'brittany',
  'amazing',
  'knowledgeable',
  'menu',
  'suggest',
  'delicious',
  'red',
  'wine',
  'even',
  'bring',
  'cute',
  'tray',
  'congratulation',
  'banner',
  'cant',
  'wait',
  'come',
  'back'],
 ['spectacular',
  'food',
  'attention',
  'detail',
  'manager',
  'john',
  'particularly',
  'friendly',
  'go',
  'beyond',
  'make',
  'night',
  'wonderful',
  'despite',
  'special',
  'occasion',
  'anything',
  'food',
  'sight',
  'lobster',
  'roll',
  'maybe',
  'best',
  'ive',
  'ever',
  'oh',
  'server',
  'brittany',
  'great',
  'everything',
  'wonderful'],
 ['go',
  'oyster',
  'happy',
  'hour',
  'raw',
  'oyster',
  'half',
  'shell',
  'super',
  'clean',
  'fresh',
  'tasty',
  'shout',
  'server',
  'alex',
  'fabulous'],
 ['around',
  'flawless',
  'experience',
  'promptly',
  'seat',
  'every',
  'food',
  'item',
  'excellent',
  'janessa',
  'go',
  'beyond',
  'ensure',
  'memorable',
  'dinner',
  'experience'],
 ['phenomenal',
  'service',
  'provide',
  'alyssa',
  'large',
  'party',
  'cant',
  'close',
  'close',
  'attentive',
  'informative',
  'kind',
  'manager',
  'josh',
  'great',
  'well',
  'team',
  'right'],
 ['best', 'meal', 'long', 'time', 'service', 'atmosphere', 'food', 'great'],
 ['love',
  'place',
  'make',
  'mom',
  'feel',
  'like',
  'star',
  'birthday',
  'shrimp',
  'la',
  'plancha',
  'octopus',
  'necessary',
  'every',
  'visit',
  'great',
  'crudo',
  'menu',
  'evolve',
  'seasonally'],
 ['great',
  'experience',
  'food',
  'service',
  'amaze',
  'get',
  'braise',
  'green',
  'one',
  'side',
  'wont',
  'regret'],
 ['easily',
  'one',
  'best',
  'meal',
  'ive',
  'atlanta',
  'add',
  'great',
  'service',
  'provide',
  'justin',
  'place',
  'favorite',
  'thank'],
 ['great',
  'place',
  'oyster',
  'seafood',
  'come',
  'celebrate',
  'hear',
  'good',
  'thing',
  'werent',
  'sure',
  'expect',
  'start',
  'oyster',
  'take',
  'time',
  'figure',
  'love',
  'salty',
  'one',
  'end',
  'list',
  'lime',
  'mignonette',
  'delicious',
  'try',
  'branzino',
  'make',
  'similar',
  'fish',
  'prepare',
  'southern',
  'india',
  'coconut',
  'though',
  'one',
  'way',
  'tasty',
  'ingredient',
  'element',
  'thick',
  'buttery',
  'gravy',
  'finish',
  'upside',
  'pineapple',
  'cake',
  'coat',
  'caramelize',
  'layer',
  'heavenly',
  'dessert',
  'wine',
  'sommelier',
  'choice',
  'great',
  'experience',
  'katie',
  'take',
  'great',
  'care',
  'u',
  'would',
  'definitely',
  'recommend'],
 ['great', 'good', 'nice', 'ambiance', 'disappoint'],
 ['fresh',
  'seafood',
  'perfectly',
  'prepare',
  'service',
  'point',
  'thoughtful',
  'touch',
  'personalize',
  'engagement',
  'guest',
  'reasonably',
  'loud',
  'atmosphere',
  'music',
  'guest',
  'chatter',
  '-',
  'challenge',
  'one',
  'person',
  'table',
  'hard',
  'hear'],
 ['warm',
  'atmosphere',
  'delicious',
  'seafood',
  'branzino',
  'must',
  'try',
  'delightful',
  'service',
  'server',
  'cj',
  'outstanding',
  'knowledgeable',
  'attentive',
  'kind',
  'looking',
  'forward',
  'next',
  'meal'],
 ['incredible',
  'experience',
  'week',
  'ago',
  'stop',
  'think',
  'server',
  'take',
  'incredible',
  'care',
  'u',
  'food',
  'unbelievable',
  'go',
  'nervous',
  'someone',
  'hasnt',
  'enjoy',
  'seafood',
  'past',
  'experience',
  'change',
  'opinion',
  'show',
  'miss',
  'enjoy',
  'oyster',
  '-',
  'many',
  'choose',
  'server',
  'brilliant',
  'job',
  'steer',
  'u',
  'towards',
  'fantastic',
  'lobster',
  'roll',
  'delicious',
  'perfect',
  'cocktail',
  'program',
  'extremely',
  'well',
  'curated'],
 ['girlfriend',
  'go',
  'optimist',
  'anniversary',
  'past',
  '3',
  'year',
  'love',
  'service',
  'apps',
  'menu',
  'drink',
  'definitely',
  'best',
  'hush',
  'puppy',
  'beignet',
  'ever',
  'shoutout',
  'server',
  'derek',
  'make',
  'anniversary',
  'date',
  'top-notch',
  'hospitality',
  'best',
  'weve',
  'optimist'],
 ['optimist',
  'top',
  '3',
  'favorite',
  'restaurant',
  'atlanta',
  'ive',
  'live',
  '10',
  'year',
  'consistently',
  'good',
  'matter',
  'get',
  'service',
  'excellent',
  'atmosphere',
  'perfect',
  'food',
  'exceptional',
  'crab',
  'soup',
  'really',
  'standout',
  'favorite',
  'oyster',
  'city'],
 ['place',
  'best',
  'food',
  'unique',
  'amaze',
  'service',
  'incredible',
  'people',
  'work',
  'kind',
  'go',
  'beyond',
  'make',
  'sure',
  'great',
  'time'],
 ['nice', 'atmosphere', 'food', 'drink', 'pricey'],
 ['pick',
  'friend',
  'nice',
  'clean',
  'modern',
  'environment',
  'parking',
  'tight',
  'worth',
  'come',
  'back',
  'entree'],
 ['great',
  'experience',
  'hubby',
  'birthday',
  'simple',
  'thing',
  'make',
  'experience',
  'amaze',
  'enter',
  'seat',
  'within',
  '1',
  'minute',
  'upon',
  'entry',
  'vibe',
  'cool',
  'casual',
  'seated',
  'notice',
  'menu',
  'say',
  'happy',
  'birthday',
  'super',
  'sweet',
  'also',
  'host',
  'kind',
  'acknowledge',
  'note',
  'reservation',
  'server',
  'kazhan',
  'b',
  'nothing',
  'short',
  'amaze',
  'menu',
  'selection',
  'give',
  'u',
  'din',
  'experience',
  'trust',
  'word',
  'selection',
  'didnt',
  'fail',
  'oyster',
  'start',
  'octopus',
  'ga',
  'peach',
  'salad',
  'entree',
  'tuna',
  'swordfish',
  'potato',
  'yummy',
  'kazhan',
  'adviced',
  'get',
  'reddish',
  'go',
  'swordfish',
  'dry',
  'im',
  'guess',
  'confit',
  'dessert',
  'delicious',
  'kind',
  'enought',
  'make',
  'hubby',
  'birthday',
  'cocktail',
  'coconut',
  'pie',
  'nice',
  'finish',
  'night',
  'kazhan',
  'personality',
  'point',
  'knowledgeable',
  'menu',
  'course',
  'food',
  'di',
  'feel',
  'overwhelm',
  'thank',
  'great',
  'experience',
  'certainly',
  'back'],
 ['5', 'star', 'category', 'deserve'],
 ['extremely',
  'excite',
  'go',
  'take',
  'out-of-town',
  'guess',
  'optimist',
  'eat',
  'remember',
  'enjoy',
  'experience',
  'however',
  'time',
  'appeal',
  'food',
  'decent',
  'nothing',
  'memorable',
  'price',
  'point',
  'suggest',
  'food',
  'delicious',
  'unfortunately',
  'wasnt',
  'experience'],
 ['excellent',
  'food',
  'vibe',
  '-',
  'server',
  'seem',
  'rush',
  'though',
  'oyster',
  'branzino',
  'excellent'],
 ['one',
  'time',
  'favorite',
  'restaurant',
  'best',
  'everything',
  'yet',
  'unpretentious',
  'live',
  'nearby',
  'like',
  'pop',
  'dinner',
  'bar',
  'whole',
  'team',
  'amazing-',
  'walter',
  'connor',
  'terick',
  'rachael',
  'professional',
  'personable',
  'highly',
  'recommend',
  'sit',
  'bar',
  'next',
  'time',
  'youre',
  'faves',
  'oyster',
  'spicy',
  'kale',
  'salad',
  'mussel',
  'branzino',
  'desert',
  'make',
  'oh',
  'burger',
  'top',
  '3',
  'city'],
 ['best',
  'seafood',
  'restaurant',
  'atlanta',
  'hand',
  'service',
  'atmosphere',
  'staff',
  'professional',
  'always',
  'eat',
  'bar',
  'tell',
  'best',
  'ever'],
 ['delicious', 'usual', 'optimist', 'never', 'miss'],
 ['simply', 'amaze'],
 ['wonderful',
  'even',
  'din',
  'room',
  'stun',
  'fill',
  'quickly',
  'wed',
  'night',
  'reservations',
  'would',
  'must',
  'din',
  '4',
  'girlfriend',
  'stick',
  'great',
  'bottle',
  'sancerre',
  'share',
  'plate',
  'oysters',
  'raw',
  'fry',
  'bake',
  'spectacular',
  'kale',
  'salad',
  'must',
  'crudo',
  'plate',
  'slso',
  'outstanding',
  'service',
  'impeccable'],
 ['place',
  'busy',
  'service',
  'quick',
  'food',
  'good',
  'top',
  'notch',
  'service',
  'waiter'],

In [ ]:
cooc_matrix = cooccurrence_matrix_sentence_generator(preproc_sentences, sentence_cooc=False, window_size=1)

Computing co-occurrences: 100%|██████████| 53566/53566 [00:02<00:00, 20078.55it/s]

                   food  good  great  service  order  place  get   go  time  \
food                146  4330   5133     2345    441    375  632  224   291
good               4330   238    202     1897    116    479  266  108   204
great              5133   202     94     3448     61   1065   95   66   288
service            2345  1897   3448       38     61     85   95  131   101
order               441   116     61       61    146    404  477  285   252
...                 ...   ...    ...      ...    ...    ...  ...  ...   ...
fastfriendlyclean     0     0      0        0      0      0    0    0     0
emcanto               0     0      0        0      0      0    0    0     0
nices                 0     0      0        0      0      0    0    0     0
niceeee               0     0      0        0      0      0    0    0     0
awssome               0     0      0        0      0      0    0    0     0

                   come  ...  goob  luvd  pizzaaaaaaa  xpenzv  xcelent  \
food                448  ...     0     0            0       0        0
good                 71  ...     0     0            0       0        0
great                45  ...     0     0            0       0        0
service              54  ...     0     0            0       0        0
order               137  ...     0     0            0       0        0
...                 ...  ...   ...   ...          ...     ...      ...
fastfriendlyclean     0  ...     0     0            0       0        0
emcanto               0  ...     0     0            0       0        0
nices                 0  ...     0     0            0       0        0
niceeee               0  ...     0     0            0       0        0
awssome               0  ...     0     0            0       0        0

                   fastfriendlyclean  emcanto  nices  niceeee  awssome
food                               0        0      0        0        0
good                               0        0      0        0        0
great                              0        0      0        0        0
service                            0        0      0        0        0
order                              0        0      0        0        0
...                              ...      ...    ...      ...      ...
fastfriendlyclean                  0        0      0        0        0
emcanto                            0        0      0        0        0
nices                              0        0      0        0        0
niceeee                            0        0      0        0        0
awssome                            0        0      0        0        0

[27219 rows x 27219 columns]

In [ ]:
display(cooc_matrix)

,food,good,great,service,order,place,get,go,time,come,...,goob,luvd,pizzaaaaaaa,xpenzv,xcelent,fastfriendlyclean,emcanto,nices,niceeee,awssome
food,146,4330,5133,2345,441,375,632,224,291,448,...,0,0,0,0,0,0,0,0,0,0
good,4330,238,202,1897,116,479,266,108,204,71,...,0,0,0,0,0,0,0,0,0,0
great,5133,202,94,3448,61,1065,95,66,288,45,...,0,0,0,0,0,0,0,0,0,0
service,2345,1897,3448,38,61,85,95,131,101,54,...,0,0,0,0,0,0,0,0,0,0
order,441,116,61,61,146,404,477,285,252,137,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fastfriendlyclean,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
emcanto,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nices,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
niceeee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
awssome,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0