<font size=10>**TASK 3 - ??**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

**Project**: *Straining the great southern Melting Pot*

**Group 8**
- Beatriz Marques 20231605
- David Carrilho 20231693
- Duarte Fernandes 20231619
- Filipe Caçador 20231707
- Mariana Calais-Pedro 20231641

*«notebook description»*

**Question**: *??*

<font color = 'red'>**IR3 – Named Entity Recognition of Culinary and Spatial Themes**
Can we automatically extract dishes and locations from restaurant reviews using Named Entity Recognition (NER), and do the patterns of these entities reveal meaningful insights about cuisine types and dining experiences?
 
(Named Entity Recognition – focusing on dishes and locations, with optional analysis of entity transitions)

----

**IR3 – Dish Entity Networks and Cuisine Clusters**
 
Can we automatically extract dishes and related entities (e.g., locations) from restaurant reviews, and do the co-occurrence patterns of these entities form meaningful clusters that reveal cuisine types and cultural links? 

(NER + Co-occurrence Analysis + Clustering)</font>

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a> 
- [1. Imports](#1)
- [2. Data](#2)
- [3. Named Entity Rcognition](#3)
    - [3.1 Specific Data Preparation](#3_1)
    - [3.2 Model Implementation](#3_2)
    - [3.3 Model Evaluation](#3_3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [2]:
import sys
import os
import pandas as pd
import spacy
from spacy import displacy
import sklearn_crfsuite
from sklearn_crfsuite import metrics
from sklearn.model_selection import train_test_split

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from my_utils import *
from visualizations import *
from general_preprocessing import *

# <font color='#BFD72F' size=6>**2. Data**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [3]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [4]:
dataset_original.head()

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...

In [5]:
dataset_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

| 🏷️ **Column Name** | 📝 **Description** |
|:-------------------|:-------------------|
|**title** | Name of the restaurant |
|**categoryName** | Labels that describe the restaurant's cuisine type |
|**website** | URL of the restaurant's webpage |
|**url** | URL of the restaurant's Google Maps page |
|**reviewsCount** | Total number of reviews for the restaurant at the time of scraping |
|**stars** | Customer rating (1 to 5) |
|**text** | Text of the review |

In [6]:
dataset = dataset_original.copy()

# <font color='#BFD72F' size=6>**3. Named Entity Recognition**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

## <font color='#BFD72F' size=6>3.1 Specific Data Preparation</font> <a class="anchor" id="3_1"></a>
  
[Back to TOC](#toc)

In [7]:
# Tokenization and POS tagging using project pipeline
dataset["pos_list"] =\
      dataset["text"].map(lambda content : main_pipeline(content,
                                                            print_output=False,
                                                            no_stopwords=False,
                                                            lowercase=False,
                                                            lemmatized=False,
                                                            no_punctuation=False,
                                                            pos_tags_list='pos_list'
                                                            ))

dataset["tokens"] =\
      dataset["text"].map(lambda content : main_pipeline(content,
                                                            print_output=False,
                                                            no_stopwords=False,
                                                            lowercase=False,
                                                            lemmatized=False,
                                                            no_punctuation=False,
                                                            tokenized_output=True
                                                            ))

In [8]:
dataset['features'] = dataset.apply(lambda row: sent2features(row['tokens'], row['pos_list']), axis=1)

In [9]:
dataset["features"].sample(1, random_state=12).iloc[0]

[{'bias': 1.0,
  'word.lower()': 'had',
  'word[-3:]': 'Had',
  'word[-2:]': 'ad',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  'BOS': True,
  '+1:word.lower()': 'my',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'PRP$',
  '+1:postag[:2]': 'PR'},
 {'bias': 1.0,
  'word.lower()': 'my',
  'word[-3:]': 'my',
  'word[-2:]': 'my',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'PRP$',
  'postag[:2]': 'PR',
  '-1:word.lower()': 'had',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'hubby',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'hubby',
  'word[-3:]': 'bby',
  'word[-2:]': 'by',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'my',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'PRP$',
  '-1:postag[:2]': 'PR',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'hubby',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': '75th',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': '75th',
  'word[-3:]': '5th',
  'word[-2:]': 'th',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'birthday',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'birthday',
  'word[-3:]': 'day',
  'word[-2:]': 'ay',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': '75th',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'at',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'at',
  'word[-3:]': 'at',
  'word[-2:]': 'at',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'birthday',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'mckendrick',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'mckendrick',
  'word[-3:]': 'ick',
  'word[-2:]': 'ck',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'at',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'mckendrick',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': ',',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': ',',
  '+1:postag[:2]': ','},
 {'bias': 1.0,
  'word.lower()': ',',
  'word[-3:]': ',',
  'word[-2:]': ',',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': ',',
  'postag[:2]': ',',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'and',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'CC',
  '+1:postag[:2]': 'CC'},
 {'bias': 1.0,
  'word.lower()': 'and',
  'word[-3:]': 'and',
  'word[-2:]': 'nd',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'CC',
  'postag[:2]': 'CC',
  '-1:word.lower()': ',',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': ',',
  '-1:postag[:2]': ',',
  '+1:word.lower()': 'it',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'PRP',
  '+1:postag[:2]': 'PR'},
 {'bias': 1.0,
  'word.lower()': 'it',
  'word[-3:]': 'it',
  'word[-2:]': 'it',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'PRP',
  'postag[:2]': 'PR',
  '-1:word.lower()': 'and',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'CC',
  '-1:postag[:2]': 'CC',
  '+1:word.lower()': 'was',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBD',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'was',
  'word[-3:]': 'was',
  'word[-2:]': 'as',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBD',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'it',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'PRP',
  '-1:postag[:2]': 'PR',
  '+1:word.lower()': 'absolutely',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'RB',
  '+1:postag[:2]': 'RB'},
 {'bias': 1.0,
  'word.lower()': 'absolutely',
  'word[-3:]': 'ely',
  'word[-2:]': 'ly',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'RB',
  'postag[:2]': 'RB',
  '-1:word.lower()': 'was',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBD',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'fabulous',
  '+1:word.istitle()': False,
  '+1:word.isupper()': True,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'fabulous',
  'word[-3:]': 'OUS',
  'word[-2:]': 'US',
  'word.isupper()': True,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'absolutely',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'RB',
  '-1:postag[:2]': 'RB',
  '+1:word.lower()': '!',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '!',
  'word[-3:]': '!',
  'word[-2:]': '!',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': 'fabulous',
  '-1:word.istitle()': False,
  '-1:word.isupper()': True,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': '!',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '!',
  'word[-3:]': '!',
  'word[-2:]': '!',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': '!',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'as',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'as',
  'word[-3:]': 'as',
  'word[-2:]': 'as',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': '!',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'as',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'dinner',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'dinner',
  'word[-3:]': 'ner',
  'word[-2:]': 'er',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': ',',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': ',',
  '+1:postag[:2]': ','},
 {'bias': 1.0,
  'word.lower()': ',',
  'word[-3:]': ',',
  'word[-2:]': ',',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': ',',
  'postag[:2]': ',',
  '-1:word.lower()': 'dinner',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'there',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'EX',
  '+1:postag[:2]': 'EX'},
 {'bias': 1.0,
  'word.lower()': 'there',
  'word[-3:]': 'ere',
  'word[-2:]': 're',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'EX',
  'postag[:2]': 'EX',
  '-1:word.lower()': ',',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': ',',
  '-1:postag[:2]': ',',
  '+1:word.lower()': 'always',
  '+1:word.istitle()': False,
  '+1:word.isupper()': True,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'always',
  'word[-3:]': 'AYS',
  'word[-2:]': 'YS',
  'word.isupper()': True,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'there',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'EX',
  '-1:postag[:2]': 'EX',
  '+1:word.lower()': '!',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '!',
  'word[-3:]': '!',
  'word[-2:]': '!',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': 'always',
  '-1:word.istitle()': False,
  '-1:word.isupper()': True,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': '!',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '!',
  'word[-3:]': '!',
  'word[-2:]': '!',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': '!',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'yepper',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'yepper',
  'word[-3:]': 'per',
  'word[-2:]': 'er',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': '!',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'it',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'PRP',
  '+1:postag[:2]': 'PR'},
 {'bias': 1.0,
  'word.lower()': 'it',
  'word[-3:]': 'it',
  'word[-2:]': 'it',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'PRP',
  'postag[:2]': 'PR',
  '-1:word.lower()': 'yepper',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'it',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'PRP',
  '-1:postag[:2]': 'PR',
  '+1:word.lower()': 'always',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'RB',
  '+1:postag[:2]': 'RB'},
 {'bias': 1.0,
  'word.lower()': 'always',
  'word[-3:]': 'ays',
  'word[-2:]': 'ys',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'RB',
  'postag[:2]': 'RB',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'great',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'great',
  'word[-3:]': 'eat',
  'word[-2:]': 'at',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'always',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'RB',
  '-1:postag[:2]': 'RB',
  '+1:word.lower()': ',',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': ',',
  '+1:postag[:2]': ','},
 {'bias': 1.0,
  'word.lower()': ',',
  'word[-3:]': ',',
  'word[-2:]': ',',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': ',',
  'postag[:2]': ',',
  '-1:word.lower()': 'great',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'all',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'PDT',
  '+1:postag[:2]': 'PD'},
 {'bias': 1.0,
  'word.lower()': 'all',
  'word[-3:]': 'all',
  'word[-2:]': 'll',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'PDT',
  'postag[:2]': 'PD',
  '-1:word.lower()': ',',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': ',',
  '-1:postag[:2]': ',',
  '+1:word.lower()': 'the',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'DT',
  '+1:postag[:2]': 'DT'},
 {'bias': 1.0,
  'word.lower()': 'the',
  'word[-3:]': 'the',
  'word[-2:]': 'he',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'DT',
  'postag[:2]': 'DT',
  '-1:word.lower()': 'all',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'PDT',
  '-1:postag[:2]': 'PD',
  '+1:word.lower()': 'ca',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'MD',
  '+1:postag[:2]': 'MD'},
 {'bias': 1.0,
  'word.lower()': 'ca',
  'word[-3:]': 'ca',
  'word[-2:]': 'ca',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'MD',
  'postag[:2]': 'MD',
  '-1:word.lower()': 'the',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'DT',
  '-1:postag[:2]': 'DT',
  '+1:word.lower()': 'not',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'RB',
  '+1:postag[:2]': 'RB'},
 {'bias': 1.0,
  'word.lower()': 'not',
  'word[-3:]': 'not',
  'word[-2:]': 'ot',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'RB',
  'postag[:2]': 'RB',
  '-1:word.lower()': 'ca',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'MD',
  '-1:postag[:2]': 'MD',
  '+1:word.lower()': 'say',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VB',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'say',
  'word[-3:]': 'say',
  'word[-2:]': 'ay',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VB',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'not',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'RB',
  '-1:postag[:2]': 'RB',
  '+1:word.lower()': 'that',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'that',
  'word[-3:]': 'hat',
  'word[-2:]': 'at',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'say',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VB',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'about',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'RB',
  '+1:postag[:2]': 'RB'},
 {'bias': 1.0,
  'word.lower()': 'about',
  'word[-3:]': 'out',
  'word[-2:]': 'ut',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'RB',
  'postag[:2]': 'RB',
  '-1:word.lower()': 'that',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'many',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'many',
  'word[-3:]': 'any',
  'word[-2:]': 'ny',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'about',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'RB',
  '-1:postag[:2]': 'RB',
  '+1:word.lower()': 'places',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NNS',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'places',
  'word[-3:]': 'ces',
  'word[-2:]': 'es',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNS',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'many',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'in',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'in',
  'word[-3:]': 'in',
  'word[-2:]': 'in',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'places',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NNS',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'atlanta.the',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'atlanta.the',
  'word[-3:]': 'The',
  'word[-2:]': 'he',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'in',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'food',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'food',
  'word[-3:]': 'ood',
  'word[-2:]': 'od',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',

In [10]:
nlp = spacy.load("en_core_web_sm")

equivalence_table = {"PERSON":"-per",
                     "NORP":"-grp",
                     "FAC":"-fac",
                     "ORG":"-org",
                     "GPE":"-gpe",
                     "LOC":"-geo",
                     "DATE":"-date",
                     "TIME":"-tim",
                     "WORK_OF_ART":"-art",
                     "LAW":"-law",
                     "LANGUAGE":"-lang",
                     "EVENT":"eve",
                     "PRODUCT":"-prod",
                     "PERCENT":"-pct",
                     "MONEY":"-mon",
                     "QUANTITY":"-qty",
                     "CARDINAL":"-card",
                     "ORDINAL":"-ord",
                     "":""
                     }

In [11]:
dataset["ner_labels_custom"] = dataset.apply(
    lambda row: align_bio_to_custom_tokens(
        row["text"], 
        row["tokens"],
        nlp,
        equivalence_table
    ),
    axis=1
)

In [12]:
# Sanity check
dataset[['text','tokens','ner_labels_custom']].head()

,text,tokens,ner_labels_custom
0,"One word amazing!! The red fish, halibut, fr...","[One, word, amazing, !, !, The, red, fish, ,, ...","[B-card, O, O, O, O, O, O, O, O, O, O, O, O, O..."
1,First time here and the food is great and the ...,"[First, time, here, and, the, food, is, great,...","[B-ord, O, O, O, O, O, O, O, O, O, O, O, O, O]"
2,I recently had the pleasure of dining at Optim...,"[I, recently, had, the, pleasure, of, dining, ...","[O, O, O, O, O, O, O, O, B-per, O, B-gpe, O, B..."
3,Beautiful atmosphere and delicious food. All o...,"[Beautiful, atmosphere, and, delicious, food, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,We had a wonderful dinner at the Optimist. Our...,"[We, had, a, wonderful, dinner, at, the, Optim...","[O, O, O, O, O, O, O, B-grp, O, O, O, O, B-car..."

In [ ]:
# # Expand rows so each token becomes its own row
# dataset["ner_labels"] = dataset.apply(
#     lambda row: align_bio(nlp(row["text"]), row["tokens"]),
#     axis=1
# )

In [16]:
# dataset.head()

## <font color='#BFD72F' size=6>3.2 Model Implementation</font> <a class="anchor" id="3_2"></a>
  
[Back to TOC](#toc)

In [17]:
# Quick (q1) train-test split that we can use to test our classifier
X_train_q1, X_test_q1, y_train_q1, y_test_q1 = train_test_split(
                                                        dataset["features"], 
                                                        dataset["ner_labels_custom"],
                                                        test_size=0.2,
                                                        random_state=39
                                                        )

train_index_q1 = list(X_train_q1.index)
test_index_q1 = list(X_test_q1.index)

In [18]:
# CRF model -> conditional random field model

crf = sklearn_crfsuite.CRF(algorithm='lbfgs', 
                           c1=0.1, 
                           c2=0.1, 
                           max_iterations=100, 
                           all_possible_transitions=True,
                           verbose=True 
                           )
try:
    crf.fit(X_train_q1, y_train_q1)
except AttributeError:
    pass

loading training data to CRFsuite: 100%|██████████| 42852/42852 [00:10<00:00, 3908.38it/s]

Feature generation
type: CRF1d
feature.minfreq: 0.000000
feature.possible_states: 0
feature.possible_transitions: 1
0....1....2....3....4....5....6....7....8....9....10
Number of features: 137043
Seconds required: 2.105

L-BFGS optimization
c1: 0.100000
c2: 0.100000
num_memories: 6
max_iterations: 100
epsilon: 0.000010
stop: 10
delta: 0.000010
linesearch: MoreThuente
linesearch.max_iterations: 20

Iter 1   time=7.01  loss=3408241.81 active=136264 feature_norm=1.00
Iter 2   time=7.20  loss=2161165.47 active=136021 feature_norm=14.90
Iter 3   time=3.60  loss=2015023.94 active=124973 feature_norm=14.04
Iter 4   time=62.01 loss=462172.08 active=84138 feature_norm=5.89
Iter 5   time=29.20 loss=385031.43 active=97761 feature_norm=5.88
Iter 6   time=61.40 loss=382929.00 active=101881 feature_norm=5.68
Iter 7   time=89.85 loss=372978.09 active=107747 feature_norm=5.67
Iter 8   time=100.48 loss=371056.01 active=108125 feature_norm=5.71
Iter 9   time=91.06 loss=368006.23 active=104889 feature_norm=5.88
Iter 10  time=34.61 loss=363555.99 active=104401 feature_norm=6.10
Iter 11  time=11.47 loss=349667.62 active=101265 feature_norm=6.31
Iter 12  time=11.45 loss=320534.17 active=98508 feature_norm=7.50
Iter 13  time=11.47 loss=273730.71 active=92789 feature_norm=11.11
Iter 14  time=11.41 loss=247542.51 active=92565 feature_norm=13.16
Iter 15  time=11.30 loss=236852.76 active=93320 feature_norm=13.40
Iter 16  time=11.38 loss=221666.59 active=91428 feature_norm=15.19
Iter 17  time=11.47 loss=206256.50 active=94575 feature_norm=15.38
Iter 18  time=11.48 loss=194126.48 active=93881 feature_norm=16.49
Iter 19  time=11.62 loss=175088.97 active=91932 feature_norm=19.24
Iter 20  time=11.56 loss=163375.13 active=90591 feature_norm=21.10
Iter 21  time=11.31 loss=154005.74 active=90484 feature_norm=22.40
Iter 22  time=11.34 loss=143737.26 active=89307 feature_norm=25.41
Iter 23  time=11.57 loss=135845.45 active=89291 feature_norm=27.36
Iter 24  time=11.40 loss=129559.78 active=88707 feature_norm=30.12
Iter 25  time=11.46 loss=121661.06 active=88081 feature_norm=34.31
Iter 26  time=11.32 loss=115736.48 active=87359 feature_norm=38.32
Iter 27  time=11.42 loss=111481.45 active=86772 feature_norm=42.34
Iter 28  time=11.44 loss=106847.81 active=86851 feature_norm=45.45
Iter 29  time=11.46 loss=103769.13 active=86780 feature_norm=47.63
Iter 30  time=11.50 loss=98495.39 active=84678 feature_norm=56.01
Iter 31  time=11.70 loss=95689.89 active=85201 feature_norm=58.43
Iter 32  time=11.37 loss=93112.91 active=85504 feature_norm=60.91
Iter 33  time=11.41 loss=90167.22 active=84887 feature_norm=65.57
Iter 34  time=11.58 loss=86147.51 active=84229 feature_norm=73.41
Iter 35  time=11.68 loss=83243.25 active=83939 feature_norm=77.73
Iter 36  time=11.51 loss=79893.46 active=83744 feature_norm=83.10
Iter 37  time=11.65 loss=76154.95 active=82688 feature_norm=92.14
Iter 38  time=11.58 loss=74293.40 active=82422 feature_norm=98.57
Iter 39  time=11.44 loss=72096.92 active=82422 feature_norm=104.32
Iter 40  time=11.43 loss=70013.00 active=82143 feature_norm=111.18
Iter 41  time=11.48 loss=67476.43 active=81812 feature_norm=118.50
Iter 42  time=11.35 loss=64989.12 active=79579 feature_norm=129.71
Iter 43  time=11.35 loss=63020.99 active=79981 feature_norm=140.21
Iter 44  time=11.46 loss=60899.65 active=79706 feature_norm=154.16
Iter 45  time=11.46 loss=59123.49 active=79687 feature_norm=164.13
Iter 46  time=11.61 loss=57221.53 active=79287 feature_norm=180.82
Iter 47  time=11.41 loss=55982.59 active=79393 feature_norm=190.76
Iter 48  time=11.26 loss=54842.43 active=78828 feature_norm=202.63
Iter 49  time=11.36 loss=53862.36 active=78898 feature_norm=212.37
Iter 50  time=11.41 loss=53136.37 active=77724 feature_norm=226.45
Iter 51  time=11.41 loss=52579.40 active=77997 feature_norm=230.32
Iter 52  time=11.46 loss=52197.92 active=77893 feature_norm=236.18
Iter 53  time=11.36 loss=51742.44 active=77543 feature_norm=242.24
Iter 54  time=11.45 loss=51458.85 active=77335 feature_norm=245.63
Iter 55  time=11.39 loss=51173.36 active=77065 feature_norm=247.90
Iter 56  time=11.46 loss=50901.82 active=76103 feature_norm=250.72
Iter 57  time=11.36 loss=50669.37 active=75676 feature_norm=250.78
Iter 58  time=11.54 loss=50436.18 active=74729 feature_norm=252.16
Iter 59  time=11.35 loss=50193.15 active=74441 feature_norm=252.74
Iter 60  time=11.69 loss=49999.61 active=74331 feature_norm=254.23
Iter 61  time=11.16 loss=49835.97 active=74201 feature_norm=254.42
Iter 62  time=11.89 loss=49664.93 active=73481 feature_norm=255.45
Iter 63  time=11.47 loss=49507.49 active=73331 feature_norm=255.54
Iter 64  time=11.45 loss=49376.58 active=73082 feature_norm=256.38
Iter 65  time=11.29 loss=49244.91 active=72944 feature_norm=256.49
Iter 66  time=11.21 loss=49118.60 active=72849 feature_norm=257.31
Iter 67  time=11.35 loss=49009.45 active=72734 feature_norm=257.47
Iter 68  time=11.21 loss=48906.51 active=72580 feature_norm=258.25
Iter 69  time=11.44 loss=48804.88 active=72239 feature_norm=258.61
Iter 70  time=11.50 loss=48715.97 active=71728 feature_norm=259.47
Iter 71  time=11.41 loss=48634.75 active=71503 feature_norm=259.73
Iter 72  time=11.34 loss=48561.53 active=71294 feature_norm=260.51
Iter 73  time=11.26 loss=48485.71 active=71127 feature_norm=260.85
Iter 74  time=11.45 loss=48420.37 active=71008 feature_norm=261.65
Iter 75  time=11.40 loss=48360.15 active=70911 feature_norm=261.87
Iter 76  time=11.38 loss=48301.17 active=70789 feature_norm=262.43
Iter 77  time=11.24 loss=48243.10 active=70557 feature_norm=262.58
Iter 78  time=11.27 loss=48187.70 active=70438 feature_norm=263.10
Iter 79  time=11.33 loss=48139.91 active=70396 feature_norm=263.09
Iter 80  time=11.36 loss=48094.12 active=70295 feature_norm=263.42
Iter 81  time=11.49 loss=48051.22 active=70208 feature_norm=263.30
Iter 82  time=11.31 loss=48008.53 active=70098 feature_norm=263.60
Iter 83  time=11.45 loss=47973.15 active=70007 feature_norm=263.42
Iter 84  time=11.41 loss=47934.87 active=69899 feature_norm=263.67
Iter 85  time=11.42 loss=47902.44 active=69784 feature_norm=263.50
Iter 86  time=11.40 loss=47870.44 active=69710 feature_norm=263.72
Iter 87  time=11.40 loss=47842.42 active=69623 feature_norm=263.53
Iter 88  time=11.48 loss=47812.54 active=69566 feature_norm=263.75
Iter 89  time=11.20 loss=47789.41 active=69472 feature_norm=263.62
Iter 90  time=11.41 loss=47760.33 active=69407 feature_norm=263.83
Iter 91  time=11.58 loss=47739.16 active=69298 feature_norm=263.73
Iter 92  time=11.11 loss=47710.95 active=69289 feature_norm=263.98
Iter 93  time=11.36 loss=47692.86 active=69222 feature_norm=263.88
Iter 94  time=11.48 loss=47666.08 active=69174 feature_norm=264.16
Iter 95  time=11.54 loss=47646.93 active=69151 feature_norm=264.08
Iter 96  time=11.52 loss=47623.97 active=69145 feature_norm=264.32
Iter 97  time=11.36 loss=47607.11 active=69100 feature_norm=264.26
Iter 98  time=11.44 loss=47586.05 active=69061 feature_norm=264.54
Iter 99  time=11.51 loss=47568.63 active=69040 feature_norm=264.50
Iter 100 time=11.45 loss=47549.39 active=68994 feature_norm=264.76
L-BFGS terminated with the maximum number of iterations
Total seconds required for training: 1514.980

Storing the model
Number of active features: 68994 (137043)
Number of active attributes: 28289 (89916)
Number of active labels: 35 (35)
Writing labels
Writing attributes
Writing feature references for transitions
Writing feature references for attributes
Seconds required: 0.100

In [19]:
# keep tokens for inspection
X_test_tokens_q1 = dataset["tokens"].loc[test_index_q1]
y_pred_q1 = crf.predict(X_test_q1)

In [ ]:
# # save model
# import joblib

# models_dir = os.path.join('..','models')
# os.makedirs(models_dir, exist_ok=True)
# joblib.dump(crf, os.path.join(models_dir, 'crf_ner_template.pkl'))

## <font color='#BFD72F' size=6>3.3 Model Evaluation</font> <a class="anchor" id="3_3"></a>
  
[Back to TOC](#toc)

In [20]:
labels = list(crf.classes_)
labels.remove("O")

round(metrics.flat_f1_score(y_test_q1, y_pred_q1,average='weighted', labels=labels), 3)

0.725

In [ ]:
sorted_labels = sorted(
    labels,
    key=lambda name: (name[1:], name[0])
)

print(sklearn_crfsuite.metrics.flat_classification_report(y_test_q1, y_pred_q1, labels=sorted_labels, digits=3))

              precision    recall  f1-score   support

       B-art      0.548     0.193     0.286        88
       I-art      0.420     0.210     0.280       100
      B-card      0.824     0.863     0.843      2122
      I-card      0.833     0.723     0.774       256
      B-date      0.845     0.832     0.839      1389
      I-date      0.846     0.833     0.839      1224
       B-fac      0.535     0.349     0.422       109
       I-fac      0.532     0.365     0.433       137
       B-geo      0.549     0.411     0.470        95
       I-geo      0.273     0.154     0.197        39
       B-gpe      0.787     0.707     0.745       998
       I-gpe      0.799     0.728     0.762       180
       B-grp      0.813     0.789     0.801       968
       I-grp      0.750     0.514     0.610        35
      B-lang      0.500     0.692     0.581        13
       B-law      0.462     0.300     0.364        20
       I-law      0.229     0.250     0.239        32
       B-mon      0.827     0.872     0.849       351
       I-mon      0.767     0.820     0.793       233
       B-ord      0.902     0.967     0.933       667
       B-org      0.632     0.472     0.540      1819
       I-org      0.544     0.487     0.514      1178
       B-pct      0.797     0.863     0.829        73
       I-pct      0.869     0.839     0.854        87
       B-per      0.718     0.621     0.666      2297
       I-per      0.642     0.483     0.551       839
      B-prod      0.587     0.239     0.340       113
      I-prod      0.000     0.000     0.000        20
       B-qty      0.923     0.720     0.809        50
       I-qty      0.932     0.631     0.752        65
       B-tim      0.845     0.829     0.837      1079
       I-tim      0.865     0.876     0.871      1263
        Beve      0.250     0.059     0.095        17
        Ieve      0.286     0.069     0.111        29

   micro avg      0.769     0.704     0.735     17985
   macro avg      0.645     0.552     0.583     17985
weighted avg      0.756     0.704     0.725     17985