<font size=10>**TASK 3 - ??**</font> <a class="anchor" id='title'></a> 

**Bachelor's in Data Science - NOVA IMS (25/26)**

**Project**: *Straining the great southern Melting Pot*

**Group 8**
- Beatriz Marques 20231605
- David Carrilho 20231693
- Duarte Fernandes 20231619
- Filipe Caçador 20231707
- Mariana Calais-Pedro 20231641

*«notebook description»*

**Question**: *??*

<font color='#BFD72' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a> 
- [1. Imports](#1)
- [2. Data](#2)
- [3. Named Entity Rcognition](#3)
    - [3.1 Specific Data Preparation](#3_1)
    - [3.2 Model Implementation](#3_2)
    - [3.3 Model Evaluation](#3_3)

# <font color='#BFD72F' size=6>**1. Imports**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

In [1]:
import warnings
%load_ext autoreload
%autoreload 2

warnings.filterwarnings('ignore')

In [39]:
import sys
import os
import pandas as pd
import spacy
from spacy import displacy
import sklearn_crfsuite
from sklearn_crfsuite import metrics
from sklearn.model_selection import train_test_split

# Get the absolute path of the source_code folder
source_code_path = os.path.abspath('../source')

# Add the source_code folder to sys.path
if source_code_path not in sys.path:
    sys.path.append(source_code_path)

from my_utils import *
from visualizations import *
from general_preprocessing import *

# <font color='#BFD72F' size=6>**2. Data**</font> <a class="anchor" id="2"></a>
  
[Back to TOC](#toc)

In [3]:
dataset_original = load_dataset('../data/atlanta_restaurant_slice_2023.csv')

In [4]:
dataset_original.head()

,title,categoryName,website,url,reviewsCount,stars,text
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...

In [5]:
dataset_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53566 entries, 0 to 53565
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         53566 non-null  object
 1   categoryName  53566 non-null  object
 2   website       50600 non-null  object
 3   url           53566 non-null  object
 4   reviewsCount  53566 non-null  int64
 5   stars         53566 non-null  float64
 6   text          53566 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ MB

| 🏷️ **Column Name** | 📝 **Description** |
|:-------------------|:-------------------|
|**title** | Name of the restaurant |
|**categoryName** | Labels that describe the restaurant's cuisine type |
|**website** | URL of the restaurant's webpage |
|**url** | URL of the restaurant's Google Maps page |
|**reviewsCount** | Total number of reviews for the restaurant at the time of scraping |
|**stars** | Customer rating (1 to 5) |
|**text** | Text of the review |

In [6]:
dataset = dataset_original.copy()

# <font color='#BFD72F' size=6>**3. Named Entity Recognition**</font> <a class="anchor" id="3"></a>
  
[Back to TOC](#toc)

## <font color='#BFD72F' size=6>3.1 Specific Data Preparation</font> <a class="anchor" id="3_1"></a>
  
[Back to TOC](#toc)

In [14]:
dataset["pos_list"] =\
      dataset["text"].map(lambda content : main_pipeline(content,
                                                            print_output=False,
                                                            no_stopwords=False,
                                                            lowercase=False,
                                                            lemmatized=False,
                                                            no_punctuation=False,
                                                            pos_tags_list='pos_list'
                                                            ))
dataset["tokens"] =\
      dataset["text"].map(lambda content : main_pipeline(content,
                                                            print_output=False,
                                                            no_stopwords=False,
                                                            lowercase=False,
                                                            lemmatized=False,
                                                            no_punctuation=False,
                                                            tokenized_output=True
                                                            ))

In [15]:
dataset

,title,categoryName,website,url,reviewsCount,stars,text,preproc_content,pos_list,tokens
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[One, word, amazing, !, !, The, red, fish, ,, ..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...,"[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[First, time, here, and, the, food, is, great,..."
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...,"[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[I, recently, had, the, pleasure, of, dining, ..."
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...,"[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[Beautiful, atmosphere, and, delicious, food, ..."
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...,"[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[We, had, a, wonderful, dinner, at, the, Optim..."
...,...,...,...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...,"[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[Friday, night, dinner, was, Chicken, Francais..."
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!,"[NNP, NNP, NNP, ., ., ., ., ., .]","[NNP, NNP, NNP, ., ., ., ., ., .]","[Great, Yay, Jordan, !, !, !, !, !, !]"
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...,"[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[Jordan, was, our, server, and, he, was, fanta..."
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...,"[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[Jordan, was, an, amazing, server, !, Great, d..."
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...,"[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[Great, food, and, service, ., Well, spaced, t..."

In [17]:
dataset["features"] = dataset.apply(lambda row : sent2features(row["tokens"], row["pos_list"]), axis=1)
dataset["features"].sample(1).iloc[0]

[{'bias': 1.0,
  'word.lower()': 'food',
  'word[-3:]': 'ood',
  'word[-2:]': 'od',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  'BOS': True,
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'food',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'excellent',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'excellent',
  'word[-3:]': 'ent',
  'word[-2:]': 'nt',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'and',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'CC',
  '+1:postag[:2]': 'CC'},
 {'bias': 1.0,
  'word.lower()': 'and',
  'word[-3:]': 'and',
  'word[-2:]': 'nd',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'CC',
  'postag[:2]': 'CC',
  '-1:word.lower()': 'excellent',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'service',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'service',
  'word[-3:]': 'ice',
  'word[-2:]': 'ce',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'and',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'CC',
  '-1:postag[:2]': 'CC',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'service',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'quick',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'quick',
  'word[-3:]': 'ick',
  'word[-2:]': 'ck',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': '.',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '.',
  'word[-3:]': '.',
  'word[-2:]': '.',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': 'quick',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'brisket',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'brisket',
  'word[-3:]': 'ket',
  'word[-2:]': 'et',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': '.',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'is',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBZ',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'is',
  'word[-3:]': 'is',
  'word[-2:]': 'is',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBZ',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'brisket',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'succulent',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'succulent',
  'word[-3:]': 'ent',
  'word[-2:]': 'nt',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'is',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBZ',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'and',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'CC',
  '+1:postag[:2]': 'CC'},
 {'bias': 1.0,
  'word.lower()': 'and',
  'word[-3:]': 'and',
  'word[-2:]': 'nd',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'CC',
  'postag[:2]': 'CC',
  '-1:word.lower()': 'succulent',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'tender',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'tender',
  'word[-3:]': 'der',
  'word[-2:]': 'er',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'and',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'CC',
  '-1:postag[:2]': 'CC',
  '+1:word.lower()': 'while',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'while',
  'word[-3:]': 'ile',
  'word[-2:]': 'le',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'tender',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'the',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'DT',
  '+1:postag[:2]': 'DT'},
 {'bias': 1.0,
  'word.lower()': 'the',
  'word[-3:]': 'the',
  'word[-2:]': 'he',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'DT',
  'postag[:2]': 'DT',
  '-1:word.lower()': 'while',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'cowboy',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NN',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'cowboy',
  'word[-3:]': 'boy',
  'word[-2:]': 'oy',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NN',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'the',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'DT',
  '-1:postag[:2]': 'DT',
  '+1:word.lower()': 'beans',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NNS',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'beans',
  'word[-3:]': 'ans',
  'word[-2:]': 'ns',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNS',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'cowboy',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NN',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'are',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'VBP',
  '+1:postag[:2]': 'VB'},
 {'bias': 1.0,
  'word.lower()': 'are',
  'word[-3:]': 'are',
  'word[-2:]': 're',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'VBP',
  'postag[:2]': 'VB',
  '-1:word.lower()': 'beans',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NNS',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'surprisingly',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'RB',
  '+1:postag[:2]': 'RB'},
 {'bias': 1.0,
  'word.lower()': 'surprisingly',
  'word[-3:]': 'gly',
  'word[-2:]': 'ly',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'RB',
  'postag[:2]': 'RB',
  '-1:word.lower()': 'are',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'VBP',
  '-1:postag[:2]': 'VB',
  '+1:word.lower()': 'delicious',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'delicious',
  'word[-3:]': 'ous',
  'word[-2:]': 'us',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'surprisingly',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'RB',
  '-1:postag[:2]': 'RB',
  '+1:word.lower()': '.',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '.',
  'word[-3:]': '.',
  'word[-2:]': '.',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': 'delicious',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'one',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'CD',
  '+1:postag[:2]': 'CD'},
 {'bias': 1.0,
  'word.lower()': 'one',
  'word[-3:]': 'One',
  'word[-2:]': 'ne',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'CD',
  'postag[:2]': 'CD',
  '-1:word.lower()': '.',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': '.',
  '-1:postag[:2]': '.',
  '+1:word.lower()': 'of',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'of',
  'word[-3:]': 'of',
  'word[-2:]': 'of',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'one',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'CD',
  '-1:postag[:2]': 'CD',
  '+1:word.lower()': 'the',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'DT',
  '+1:postag[:2]': 'DT'},
 {'bias': 1.0,
  'word.lower()': 'the',
  'word[-3:]': 'the',
  'word[-2:]': 'he',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'DT',
  'postag[:2]': 'DT',
  '-1:word.lower()': 'of',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'hidden',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'JJ',
  '+1:postag[:2]': 'JJ'},
 {'bias': 1.0,
  'word.lower()': 'hidden',
  'word[-3:]': 'den',
  'word[-2:]': 'en',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'JJ',
  'postag[:2]': 'JJ',
  '-1:word.lower()': 'the',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'DT',
  '-1:postag[:2]': 'DT',
  '+1:word.lower()': 'gems',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'NNS',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'gems',
  'word[-3:]': 'ems',
  'word[-2:]': 'ms',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNS',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'hidden',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'JJ',
  '-1:postag[:2]': 'JJ',
  '+1:word.lower()': 'of',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'of',
  'word[-3:]': 'of',
  'word[-2:]': 'of',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'gems',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'NNS',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'bbq',
  '+1:word.istitle()': False,
  '+1:word.isupper()': True,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'bbq',
  'word[-3:]': 'BBQ',
  'word[-2:]': 'BQ',
  'word.isupper()': True,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'of',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': 'in',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': 'IN',
  '+1:postag[:2]': 'IN'},
 {'bias': 1.0,
  'word.lower()': 'in',
  'word[-3:]': 'in',
  'word[-2:]': 'in',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': 'IN',
  'postag[:2]': 'IN',
  '-1:word.lower()': 'bbq',
  '-1:word.istitle()': False,
  '-1:word.isupper()': True,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  '+1:word.lower()': 'georgia',
  '+1:word.istitle()': True,
  '+1:word.isupper()': False,
  '+1:postag': 'NNP',
  '+1:postag[:2]': 'NN'},
 {'bias': 1.0,
  'word.lower()': 'georgia',
  'word[-3:]': 'gia',
  'word[-2:]': 'ia',
  'word.isupper()': False,
  'word.istitle()': True,
  'word.isdigit()': False,
  'postag': 'NNP',
  'postag[:2]': 'NN',
  '-1:word.lower()': 'in',
  '-1:word.istitle()': False,
  '-1:word.isupper()': False,
  '-1:postag': 'IN',
  '-1:postag[:2]': 'IN',
  '+1:word.lower()': '.',
  '+1:word.istitle()': False,
  '+1:word.isupper()': False,
  '+1:postag': '.',
  '+1:postag[:2]': '.'},
 {'bias': 1.0,
  'word.lower()': '.',
  'word[-3:]': '.',
  'word[-2:]': '.',
  'word.isupper()': False,
  'word.istitle()': False,
  'word.isdigit()': False,
  'postag': '.',
  'postag[:2]': '.',
  '-1:word.lower()': 'georgia',
  '-1:word.istitle()': True,
  '-1:word.isupper()': False,
  '-1:postag': 'NNP',
  '-1:postag[:2]': 'NN',
  'EOS': True}]

In [22]:
# Expand rows so each token becomes its own row

dataset["ner_labels"] = dataset.apply(
    lambda row: align_bio(nlp(row["text"]), row["tokens"]),
    axis=1
)

In [24]:
dataset

,title,categoryName,website,url,reviewsCount,stars,text,preproc_content,pos_list,tokens,features,ner_labels
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[One, word, amazing, !, !, The, red, fish, ,, ...","[{'bias': 1.0, 'word.lower()': 'one', 'word[-3...","[B-CARDINAL, O, O, O, O, O, O, O, O, O, O, O, ..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...,"[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[First, time, here, and, the, food, is, great,...","[{'bias': 1.0, 'word.lower()': 'first', 'word[...","[B-ORDINAL, O, O, O, O, O, O, O, O, O, O, O, O..."
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...,"[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[I, recently, had, the, pleasure, of, dining, ...","[{'bias': 1.0, 'word.lower()': 'i', 'word[-3:]...","[O, O, O, O, O, O, O, O, B-PERSON, O, B-GPE, O..."
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...,"[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[Beautiful, atmosphere, and, delicious, food, ...","[{'bias': 1.0, 'word.lower()': 'beautiful', 'w...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...,"[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[We, had, a, wonderful, dinner, at, the, Optim...","[{'bias': 1.0, 'word.lower()': 'we', 'word[-3:...","[O, O, O, O, O, O, O, B-NORP, O, O, O, O, B-CA..."
...,...,...,...,...,...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...,"[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[Friday, night, dinner, was, Chicken, Francais...","[{'bias': 1.0, 'word.lower()': 'friday', 'word...","[B-TIME, I-TIME, O, O, B-PERSON, I-PERSON, O, ..."
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!,"[NNP, NNP, NNP, ., ., ., ., ., .]","[NNP, NNP, NNP, ., ., ., ., ., .]","[Great, Yay, Jordan, !, !, !, !, !, !]","[{'bias': 1.0, 'word.lower()': 'great', 'word[...","[O, O, B-PERSON, O, O, O, O, O, O]"
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...,"[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[Jordan, was, our, server, and, he, was, fanta...","[{'bias': 1.0, 'word.lower()': 'jordan', 'word...","[B-PERSON, O, O, O, O, O, O, O, O, O, O, O]"
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...,"[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[Jordan, was, an, amazing, server, !, Great, d...","[{'bias': 1.0, 'word.lower()': 'jordan', 'word...","[B-PERSON, O, O, O, O, O, O, O, O, O, O, O, O,..."
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...,"[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[Great, food, and, service, ., Well, spaced, t...","[{'bias': 1.0, 'word.lower()': 'great', 'word[...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]"

In [34]:
nlp = spacy.load("en_core_web_sm")
equivalence_table = {"PERSON":"-per",
                     "NORP":"-grp",
                     "FAC":"-fac",
                     "ORG":"-org",
                     "GPE":"-gpe",
                     "LOC":"-geo",
                     "DATE":"-date",
                     "TIME":"-tim",
                     "WORK_OF_ART":"-art",
                     "LAW":"-law",
                     "LANGUAGE":"-lang",
                     "EVENT":"eve",
                     "PRODUCT":"-prod",
                     "PERCENT":"-pct",
                     "MONEY":"-mon",
                     "QUANTITY":"-qty",
                     "CARDINAL":"-card",
                     "ORDINAL":"-ord",
                     "":""
                     }

dataset["ner_labels_custom"] = dataset.apply(
    lambda row: align_bio_to_custom_tokens(
        row["text"], 
        row["tokens"],
        nlp,
        equivalence_table
    ),
    axis=1
)

In [35]:
dataset

,title,categoryName,website,url,reviewsCount,stars,text,preproc_content,pos_list,tokens,features,ner_labels,ner_labels_custom
0,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,"One word amazing!! The red fish, halibut, fr...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[CD, NN, NN, ., ., DT, JJ, NN, ,, NN, ,, VBN, ...","[One, word, amazing, !, !, The, red, fish, ,, ...","[{'bias': 1.0, 'word.lower()': 'one', 'word[-3...","[B-CARDINAL, O, O, O, O, O, O, O, O, O, O, O, ...","[B-card, O, O, O, O, O, O, O, O, O, O, O, O, O..."
1,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,First time here and the food is great and the ...,"[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[JJ, NN, RB, CC, DT, NN, VBZ, JJ, CC, DT, NN, ...","[First, time, here, and, the, food, is, great,...","[{'bias': 1.0, 'word.lower()': 'first', 'word[...","[B-ORDINAL, O, O, O, O, O, O, O, O, O, O, O, O...","[B-ord, O, O, O, O, O, O, O, O, O, O, O, O, O]"
2,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,I recently had the pleasure of dining at Optim...,"[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[PRP, RB, VBD, DT, NN, IN, VBG, IN, NNP, IN, N...","[I, recently, had, the, pleasure, of, dining, ...","[{'bias': 1.0, 'word.lower()': 'i', 'word[-3:]...","[O, O, O, O, O, O, O, O, B-PERSON, O, B-GPE, O...","[O, O, O, O, O, O, O, O, B-per, O, B-gpe, O, B..."
3,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,Beautiful atmosphere and delicious food. All o...,"[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[NNP, RB, CC, JJ, NN, ., DT, IN, DT, NN, NN, N...","[Beautiful, atmosphere, and, delicious, food, ...","[{'bias': 1.0, 'word.lower()': 'beautiful', 'w...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,The Optimist,Seafood restaurant,https://www.theoptimistrestaurant.com/,https://www.google.com/maps/place/The+Optimist...,3349,5.0,We had a wonderful dinner at the Optimist. Our...,"[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[PRP, VBD, DT, JJ, NN, IN, DT, NNP, ., PRP$, N...","[We, had, a, wonderful, dinner, at, the, Optim...","[{'bias': 1.0, 'word.lower()': 'we', 'word[-3:...","[O, O, O, O, O, O, O, B-NORP, O, O, O, O, B-CA...","[O, O, O, O, O, O, O, B-grp, O, O, O, O, B-car..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53561,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Friday night dinner was Chicken Francaise. Jor...,"[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[NNP, NN, NN, VBD, NNP, NNP, ., NNP, VBD, DT, ...","[Friday, night, dinner, was, Chicken, Francais...","[{'bias': 1.0, 'word.lower()': 'friday', 'word...","[B-TIME, I-TIME, O, O, B-PERSON, I-PERSON, O, ...","[B-tim, I-tim, O, O, B-per, I-per, O, B-per, O..."
53562,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great dinner.... Yay Jordan!!!!!!,"[NNP, NNP, NNP, ., ., ., ., ., .]","[NNP, NNP, NNP, ., ., ., ., ., .]","[Great, Yay, Jordan, !, !, !, !, !, !]","[{'bias': 1.0, 'word.lower()': 'great', 'word[...","[O, O, B-PERSON, O, O, O, O, O, O]","[O, O, B-per, O, O, O, O, O, O]"
53563,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was our server and he was fantastic! Gr...,"[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[NNP, VBD, PRP$, NN, CC, PRP, VBD, JJ, ., JJ, ...","[Jordan, was, our, server, and, he, was, fanta...","[{'bias': 1.0, 'word.lower()': 'jordan', 'word...","[B-PERSON, O, O, O, O, O, O, O, O, O, O, O]","[B-per, O, O, O, O, O, O, O, O, O, O, O]"
53564,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Jordan was an amazing server! Great delicious...,"[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[NNP, VBD, DT, JJ, NN, ., NNP, JJ, NN, CC, NN,...","[Jordan, was, an, amazing, server, !, Great, d...","[{'bias': 1.0, 'word.lower()': 'jordan', 'word...","[B-PERSON, O, O, O, O, O, O, O, O, O, O, O, O,...","[B-per, O, O, O, O, O, O, O, O, O, O, O, O, O,..."
53565,L On North,New American restaurant,https://www.lonnorth.com/?utm_source=google&ut...,https://www.google.com/maps/place/L+On+North/@...,449,5.0,Great food and service. Well spaced tables a...,"[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[NNP, NN, CC, NN, ., NNP, VBD, NNS, CC, JJ, NN...","[Great, food, and, service, ., Well, spaced, t...","[{'bias': 1.0, 'word.lower()': 'great', 'word[...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, O]"

## <font color='#BFD72F' size=6>3.2 Model Implementation</font> <a class="anchor" id="3_2"></a>
  
[Back to TOC](#toc)

In [41]:
#Create a quick (q1) train-test split that we can use to test our classifier
X_train_q1, X_test_q1, y_train_q1, y_test_q1 = train_test_split(dataset["features"], dataset["ner_labels_custom"],
                                                    test_size=0.2, random_state=39)

train_index_q1 = list(X_train_q1.index)
test_index_q1 = list(X_test_q1.index)

crf = sklearn_crfsuite.CRF(algorithm='lbfgs', 
                           c1=0.1, 
                           c2=0.1, 
                           max_iterations=100, 
                           all_possible_transitions=True,
                           verbose=True 
                           )
try:
    crf.fit(X_train_q1, y_train_q1)
except AttributeError:
    pass

X_test_tokens_q1 = dataset["tokens"].loc[test_index_q1]

y_pred_q1 = crf.predict(X_test_q1)

loading training data to CRFsuite: 100%|██████████| 42852/42852 [00:30<00:00, 1403.71it/s]

Feature generation
type: CRF1d
feature.minfreq: 0.000000
feature.possible_states: 0
feature.possible_transitions: 1
0....1....2....3....4....5....6....7....8....9....10
Number of features: 137038
Seconds required: 3.718

L-BFGS optimization
c1: 0.100000
c2: 0.100000
num_memories: 6
max_iterations: 100
epsilon: 0.000010
stop: 10
delta: 0.000010
linesearch: MoreThuente
linesearch.max_iterations: 20

Iter 1   time=14.54 loss=3408241.87 active=136259 feature_norm=1.00
Iter 2   time=14.82 loss=2161165.49 active=136015 feature_norm=14.90
Iter 3   time=7.14  loss=2015023.96 active=124968 feature_norm=14.04
Iter 4   time=117.89 loss=462174.63 active=84140 feature_norm=5.89
Iter 5   time=56.56 loss=385032.07 active=97763 feature_norm=5.88
Iter 6   time=71.23 loss=382926.62 active=101882 feature_norm=5.68
Iter 7   time=56.49 loss=372977.97 active=107746 feature_norm=5.67
Iter 8   time=63.33 loss=371057.44 active=108124 feature_norm=5.71
Iter 9   time=56.11 loss=368005.49 active=104890 feature_norm=5.88
Iter 10  time=21.37 loss=363557.12 active=104401 feature_norm=6.10
Iter 11  time=7.09  loss=349668.63 active=101265 feature_norm=6.31
Iter 12  time=7.11  loss=320533.62 active=98508 feature_norm=7.50
Iter 13  time=7.01  loss=273732.26 active=92789 feature_norm=11.11
Iter 14  time=6.90  loss=247542.54 active=92565 feature_norm=13.16
Iter 15  time=6.99  loss=236853.61 active=93323 feature_norm=13.40
Iter 16  time=6.98  loss=221669.72 active=91429 feature_norm=15.19
Iter 17  time=7.12  loss=206257.77 active=94575 feature_norm=15.38
Iter 18  time=7.38  loss=194129.90 active=93882 feature_norm=16.49
Iter 19  time=6.96  loss=175091.11 active=91933 feature_norm=19.24
Iter 20  time=7.03  loss=163377.13 active=90589 feature_norm=21.10
Iter 21  time=7.80  loss=154008.43 active=90481 feature_norm=22.39
Iter 22  time=7.23  loss=143740.17 active=89308 feature_norm=25.41
Iter 23  time=7.00  loss=135847.45 active=89287 feature_norm=27.36
Iter 24  time=6.91  loss=129563.51 active=88704 feature_norm=30.12
Iter 25  time=6.96  loss=121670.57 active=88077 feature_norm=34.30
Iter 26  time=7.01  loss=115740.18 active=87353 feature_norm=38.31
Iter 27  time=6.96  loss=111490.97 active=86766 feature_norm=42.34
Iter 28  time=6.95  loss=106859.27 active=86851 feature_norm=45.45
Iter 29  time=7.04  loss=103796.09 active=86783 feature_norm=47.61
Iter 30  time=7.12  loss=98531.02 active=84691 feature_norm=55.95
Iter 31  time=7.13  loss=95637.32 active=85214 feature_norm=58.26
Iter 32  time=6.93  loss=93195.33 active=85443 feature_norm=60.68
Iter 33  time=6.91  loss=90116.34 active=84767 feature_norm=65.59
Iter 34  time=6.90  loss=86124.39 active=84135 feature_norm=73.43
Iter 35  time=6.88  loss=83117.47 active=83841 feature_norm=78.04
Iter 36  time=7.02  loss=79793.54 active=83676 feature_norm=83.34
Iter 37  time=8.11  loss=76048.67 active=82387 feature_norm=92.96
Iter 38  time=7.94  loss=74110.95 active=82467 feature_norm=97.67
Iter 39  time=7.10  loss=71743.38 active=82192 feature_norm=104.78
Iter 40  time=7.00  loss=69393.21 active=82134 feature_norm=111.51
Iter 41  time=6.93  loss=67257.05 active=80355 feature_norm=126.81
Iter 42  time=6.99  loss=65595.53 active=81165 feature_norm=129.79
Iter 43  time=6.97  loss=64476.20 active=80598 feature_norm=134.39
Iter 44  time=7.02  loss=61345.11 active=79069 feature_norm=154.85
Iter 45  time=7.00  loss=60180.00 active=79529 feature_norm=162.83
Iter 46  time=7.01  loss=58845.28 active=79688 feature_norm=169.99
Iter 47  time=6.99  loss=56764.22 active=79354 feature_norm=188.74
Iter 48  time=14.10 loss=56505.74 active=79331 feature_norm=194.65
Iter 49  time=6.96  loss=55267.12 active=79517 feature_norm=199.18
Iter 50  time=7.07  loss=54361.17 active=79128 feature_norm=208.46
Iter 51  time=7.13  loss=53584.92 active=78630 feature_norm=220.33
Iter 52  time=7.03  loss=52928.19 active=78706 feature_norm=222.71
Iter 53  time=6.95  loss=52478.55 active=78567 feature_norm=228.71
Iter 54  time=6.95  loss=51963.82 active=77547 feature_norm=233.95
Iter 55  time=6.97  loss=51662.49 active=77379 feature_norm=239.37
Iter 56  time=6.99  loss=51375.28 active=77292 feature_norm=241.37
Iter 57  time=7.20  loss=51071.60 active=76607 feature_norm=244.63
Iter 58  time=6.96  loss=50810.22 active=75647 feature_norm=246.89
Iter 59  time=7.43  loss=50568.45 active=75578 feature_norm=249.01
Iter 60  time=7.05  loss=50363.89 active=74878 feature_norm=249.61
Iter 61  time=6.99  loss=50124.77 active=73356 feature_norm=251.62
Iter 62  time=7.01  loss=49926.15 active=73514 feature_norm=251.67
Iter 63  time=7.12  loss=49757.37 active=73397 feature_norm=252.71
Iter 64  time=7.08  loss=49548.77 active=73164 feature_norm=253.53
Iter 65  time=7.02  loss=49401.81 active=73096 feature_norm=254.98
Iter 66  time=7.25  loss=49269.33 active=72907 feature_norm=255.31
Iter 67  time=6.96  loss=49124.87 active=72598 feature_norm=256.51
Iter 68  time=6.92  loss=48998.61 active=72381 feature_norm=257.04
Iter 69  time=7.02  loss=48889.34 active=72212 feature_norm=258.13
Iter 70  time=7.11  loss=48788.30 active=72101 feature_norm=258.50
Iter 71  time=7.12  loss=48692.46 active=71983 feature_norm=259.45
Iter 72  time=6.93  loss=48605.21 active=71743 feature_norm=259.74
Iter 73  time=7.00  loss=48525.94 active=71510 feature_norm=260.49
Iter 74  time=6.96  loss=48447.24 active=71277 feature_norm=260.75
Iter 75  time=7.16  loss=48375.29 active=71093 feature_norm=261.53
Iter 76  time=7.12  loss=48314.70 active=71005 feature_norm=261.71
Iter 77  time=7.00  loss=48256.03 active=70886 feature_norm=262.23
Iter 78  time=7.08  loss=48199.36 active=70794 feature_norm=262.38
Iter 79  time=7.08  loss=48148.37 active=70645 feature_norm=262.89
Iter 80  time=7.05  loss=48102.20 active=70522 feature_norm=262.92
Iter 81  time=7.00  loss=48056.68 active=70401 feature_norm=263.28
Iter 82  time=7.02  loss=48011.96 active=70245 feature_norm=263.30
Iter 83  time=7.01  loss=47970.24 active=70147 feature_norm=263.69
Iter 84  time=7.13  loss=47932.99 active=70109 feature_norm=263.61
Iter 85  time=7.15  loss=47897.65 active=70023 feature_norm=263.90
Iter 86  time=6.96  loss=47863.96 active=69934 feature_norm=263.84
Iter 87  time=7.05  loss=47830.96 active=69837 feature_norm=264.08
Iter 88  time=7.12  loss=47802.99 active=69742 feature_norm=263.99
Iter 89  time=7.12  loss=47771.16 active=69709 feature_norm=264.27
Iter 90  time=6.99  loss=47745.64 active=69619 feature_norm=264.18
Iter 91  time=7.01  loss=47716.16 active=69597 feature_norm=264.39
Iter 92  time=7.05  loss=47694.97 active=69503 feature_norm=264.30
Iter 93  time=7.01  loss=47668.79 active=69408 feature_norm=264.57
Iter 94  time=7.24  loss=47648.01 active=69342 feature_norm=264.48
Iter 95  time=6.99  loss=47622.30 active=69321 feature_norm=264.70
Iter 96  time=7.08  loss=47604.02 active=69252 feature_norm=264.64
Iter 97  time=7.04  loss=47582.53 active=69181 feature_norm=264.84
Iter 98  time=7.18  loss=47567.19 active=69143 feature_norm=264.75
Iter 99  time=6.92  loss=47545.69 active=69098 feature_norm=265.02
Iter 100 time=7.02  loss=47528.04 active=69080 feature_norm=264.93
L-BFGS terminated with the maximum number of iterations
Total seconds required for training: 1122.699

Storing the model
Number of active features: 69080 (137038)
Number of active attributes: 28348 (89911)
Number of active labels: 35 (35)
Writing labels
Writing attributes
Writing feature references for transitions
Writing feature references for attributes
Seconds required: 0.051

## <font color='#BFD72F' size=6>3.3 Model Evaluation</font> <a class="anchor" id="3_3"></a>
  
[Back to TOC](#toc)

In [42]:
labels = list(crf.classes_)
labels.remove("O")

round(metrics.flat_f1_score(y_test_q1, y_pred_q1,average='weighted', labels=labels), 3)

0.722

In [43]:
sorted_labels = sorted(
    labels,
    key=lambda name: (name[1:], name[0])
)

print(sklearn_crfsuite.metrics.flat_classification_report(y_test_q1, y_pred_q1, labels=sorted_labels, digits=3))

              precision    recall  f1-score   support

       B-art      0.630     0.193     0.296        88
       I-art      0.615     0.240     0.345       100
      B-card      0.823     0.861     0.841      2122
      I-card      0.821     0.719     0.767       256
      B-date      0.847     0.826     0.836      1389
      I-date      0.850     0.824     0.837      1224
       B-fac      0.533     0.367     0.435       109
       I-fac      0.520     0.387     0.444       137
       B-geo      0.480     0.379     0.424        95
       I-geo      0.214     0.154     0.179        39
       B-gpe      0.796     0.704     0.747       998
       I-gpe      0.801     0.717     0.757       180
       B-grp      0.812     0.787     0.800       968
       I-grp      0.818     0.514     0.632        35
      B-lang      0.500     0.615     0.552        13
       B-law      0.600     0.300     0.400        20
       I-law      0.471     0.250     0.327        32
       B-mon      0.826     0.866     0.846       351
       I-mon      0.797     0.794     0.796       233
       B-ord      0.902     0.969     0.934       667
       B-org      0.636     0.463     0.536      1819
       I-org      0.546     0.467     0.503      1178
       B-pct      0.785     0.849     0.816        73
       I-pct      0.867     0.828     0.847        87
       B-per      0.725     0.608     0.661      2297
       I-per      0.643     0.462     0.538       839
      B-prod      0.596     0.248     0.350       113
      I-prod      0.000     0.000     0.000        20
       B-qty      0.919     0.680     0.782        50
       I-qty      0.927     0.585     0.717        65
       B-tim      0.844     0.828     0.836      1079
       I-tim      0.870     0.876     0.873      1263
        Beve      0.000     0.000     0.000        17
        Ieve      0.000     0.000     0.000        29

   micro avg      0.773     0.696     0.733     17985
   macro avg      0.648     0.540     0.578     17985
weighted avg      0.760     0.696     0.722     17985